#include <stdio.h>
#include <string.h>
#include <math.h>

#include "comm.h"
#include "db.h"
#include "events.h"
#include "interp.h"
#include "mm.h"
#include "new_combat_def.h"
#include "prototypes.h"
#include "spells.h"
#include "structs.h"
#include "utils.h"
#include "arena.h"
#include "arenadef.h"
#include "justice.h"
#include "weather.h"
#include "sound.h"
#include "objmisc.h"
#include "tradeskill.h"


struct forge_item forge_item_list[MAX_FORGE_ITEMS] = {
   //THIS FIRST IS UNUSED
   {0, "armor mithril", "an mithril platemail forged by $s lies here.&n",
       "%s mithril platemail&n",
       {LARGE_MITHRIL_ORE, 0,0,0,0},
       APPLY_DAMROLL, 0,0,
       APPLY_HITROLL, 0,3,
       1,100,
       ALLOW,
       CLASS_WARRIOR |CLASS_MERCENARY,
       ITEM_WEAR_BODY,
       0,0,0,0,
   },
{1, "crude iron plate leggings",
 "&+LSome &+bcrude &+ciron &+Lplate leggings forged by &+W%s &+Llie here.&n",
 "&+Lsome &+bcrude &+ciron &+Lplate leggings&n",
      {MEDIUM_IRON_ORE, SMALL_IRON_ORE,0,0,0},
      APPLY_DAMROLL, 1,1,
      APPLY_HITROLL, 1,1,
      1,100,
      ALLOW,
      CLASS_WARRIOR|CLASS_MERCENARY|CLASS_ANTIPALADIN|CLASS_PALADIN,
      ITEM_WEAR_LEGS,
	0,0,0,0,
  },
  {2, "crude iron plate sleeves",
 "&+LSome &+bcrude &+ciron &+Lplate sleeves forged by &+W%s &+Llie here.&n",
 "&+Lsome &+bcrude &+ciron &+Lplate sleeves&n",
      {MEDIUM_IRON_ORE, SMALL_IRON_ORE,0,0,0},
      APPLY_DAMROLL, 1,1,
      APPLY_HITROLL, 0,1,
      1,100,
      ALLOW,
      CLASS_WARRIOR|CLASS_MERCENARY|CLASS_ANTIPALADIN|CLASS_PALADIN,
      ITEM_WEAR_ARMS,
	0,0,0,0,
  },
  {3, "crude iron plate battle helm",
 "&+LSome &+bcrude &+ciron &+Lplate b&+wa&+Wtt&+wl&+Le helm forged by &+W%s &+Llie here.&n",
 "&+Lsome &+bcrude &+ciron &+Lplate b&+wa&+Wtt&+wl&+Lehelm&n",
      {MEDIUM_IRON_ORE, MEDIUM_IRON_ORE,0,0,0},
      APPLY_DAMROLL, 1,1,
      APPLY_HITROLL, 1,2,
      1,100,
      ALLOW,
      CLASS_WARRIOR|CLASS_MERCENARY|CLASS_ANTIPALADIN|CLASS_PALADIN,
      ITEM_WEAR_HEAD,
	0,0,0,0,
  },
  {4, "crude iron plate gauntlets",
 "&+LSome &+bcrude &+ciron &+Lplate gauntlets&+L lie here.&n",
 "&+Lsome &+bcrude &+ciron &+Lplate gauntlets&n",
      {MEDIUM_IRON_ORE, MEDIUM_IRON_ORE,0,0,0},
      APPLY_DAMROLL, 1,2,
      APPLY_HITROLL, 1,1,
      1,100,
      ALLOW,
      CLASS_WARRIOR|CLASS_MERCENARY|CLASS_ANTIPALADIN|CLASS_PALADIN,
      ITEM_WEAR_HANDS,
	0,0,0,0,
  },
 {5, "crude iron plate platemail",
 "&+LSome &+bcrude &+ciron &+Lplatemail forged by &+W%s &+Llies here.&n",
 "&+Lsome &+bcrude &+ciron &+Lplatemail &n",
      {LARGE_IRON_ORE, LARGE_IRON_ORE,LARGE_IRON_ORE,0,0},
      APPLY_DAMROLL, 1,1,
      APPLY_HITROLL, 1,1,
      1,100,
      ALLOW,
      CLASS_WARRIOR|CLASS_MERCENARY|CLASS_ANTIPALADIN|CLASS_PALADIN,
      ITEM_WEAR_BODY,
	0,0,0,0,
  },
  {6, "crude copper mesh leggings",
 "&+yA pair of cr&+Yud&+ye &+ycopper &+ym&+Ye&+ys&+Yh&+y leggings sit here.&n",
 "&+ya pair of cr&+Yud&+ye &+ycopper &+ym&+Ye&+ys&+Yh&+y leggings&n",
      {MEDIUM_COPPER_ORE, SMALL_COPPER_ORE,0,0,0},
      APPLY_HITROLL, 1,2,
      APPLY_HIT, 5,10,
      1,100,
      ALLOW,
      CLASS_WARRIOR|CLASS_MERCENARY|CLASS_ANTIPALADIN|CLASS_PALADIN,
      ITEM_WEAR_LEGS,
	0,0,0,0,
  },
  {7, "crude copper mesh sleeves",
 "&+yA pair of cr&+Yud&+ye &+ycopper &+ym&+Ye&+ys&+Yh&+y sleeves &+Llie here.&n",
 "&+ya pair of cr&+Yud&+ye &+ycopper &+ym&+Ye&+ys&+Yh&+y sleeves&n",
      {MEDIUM_COPPER_ORE, SMALL_COPPER_ORE,0,0,0},
      APPLY_HITROLL, 1,2,
      APPLY_HIT, 3,8,
      1,100,
      ALLOW,
      CLASS_WARRIOR|CLASS_MERCENARY|CLASS_ANTIPALADIN|CLASS_PALADIN,
      ITEM_WEAR_ARMS,
	0,0,0,0,
  },
  {8, "crude bronze mesh coif",
 "&+yA cr&+Yud&+ye &+ycopper &+ym&+Ye&+ys&+Yh&+y coif &+Llies here.&n",
 "&+ya cr&+Yud&+ye &+ycopper &+ym&+Ye&+ys&+Yh&+y coif&n",
      {MEDIUM_COPPER_ORE, SMALL_COPPER_ORE,0,0,0},
      APPLY_HITROLL, 1,2,
      APPLY_HIT, 3,8,
      1,100,
      ALLOW,
      CLASS_WARRIOR|CLASS_MERCENARY|CLASS_ANTIPALADIN|CLASS_PALADIN,
      ITEM_WEAR_HEAD,
	0,0,0,0,
  },
  {9, "crude bronze mesh gauntlets",
 "&+yA pair of cr&+Yud&+ye &+ycopper &+ym&+Ye&+ys&+Yh&+y gauntlets &+Llie here.&n",
 "&+ya pair of cr&+Yud&+ye &+ycopper&+ym&+Ye&+ys&+Yh&+y gauntlets&n",
      {MEDIUM_COPPER_ORE, MEDIUM_COPPER_ORE,0,0,0},
      APPLY_HITROLL, 1,2,
      APPLY_HIT, 3,8,
      1,100,
      ALLOW,
      CLASS_WARRIOR|CLASS_MERCENARY|CLASS_ANTIPALADIN|CLASS_PALADIN,
      ITEM_WEAR_HANDS,
	0,0,0,0,
  },
  {10, "crude copper mesh shirt",
 "&+yA cr&+Yud&+ye &+ycopper &+ym&+Ye&+ys&+Yh&+y shirt &+Llies here.&n",
 "&+ya cr&+Yud&+ye &+ycopper &+ym&+Ye&+ys&+Yh&+y shirt&n",
      {LARGE_COPPER_ORE, SMALL_COPPER_ORE,0,0,0},
      APPLY_HITROLL, 1,2,
      APPLY_HIT, 3,8,
      1,100,
      ALLOW,
      CLASS_WARRIOR|CLASS_MERCENARY|CLASS_ANTIPALADIN|CLASS_PALADIN,
      ITEM_WEAR_BODY,
	0,0,0,0,
  },
{11, "coarse iron mantle",
     "&+LA&+w coarse&+c iron&+L mantle lies here.&n",
     "&+La &+wcoarse&+c iron&+L mantle&n",
      {MEDIUM_IRON_ORE, SMALL_IRON_ORE,
      SMALL_IRON_ORE,0,0},
      APPLY_DAMROLL, 1,1,
      APPLY_HITROLL, 1,1,
      1,100,
      ALLOW,
      CLASS_WARRIOR|CLASS_MERCENARY|CLASS_ANTIPALADIN|CLASS_PALADIN|CLASS_BERSERKER,
      ITEM_WEAR_ABOUT,
	0,0,0,0,
  },
{12, "coarse iron sabatons",
      "&+LSome &+wcoarse&+c iron&+L sabatons lie here.&n",
      "&+Lsome &+wcoarse&+c iron&+L sabtons&n",
      {SMALL_IRON_ORE,SMALL_IRON_ORE,SMALL_IRON_ORE,0,0},
      APPLY_DAMROLL, 1,1,
      APPLY_HITROLL, 1,1,
      1,100,
      ALLOW,
      CLASS_WARRIOR|CLASS_MERCENARY|CLASS_ANTIPALADIN|CLASS_PALADIN|CLASS_THIEF|CLASS_ASSASSIN|CLASS_ALCHEMIST,
      ITEM_WEAR_FEET,
	0,0,0,0,
  },
{13, "sturdy iron gauntlets",
     "&+LA pair of &+Csturdy&+c iron&+L gauntlets collect dust here.&n",
     "&+La pair of &+Csturdy&+c iron&+L gauntlets&n",
      {MEDIUM_IRON_ORE, MEDIUM_IRON_ORE,SMALL_IRON_ORE,0,0},
      APPLY_DAMROLL, 1,1,
      APPLY_HITROLL, 1,2,
      20,100,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_HANDS,
	0,0,0,0,
  },
{14, "sturdy iron great helm",
     "&+LA &+Csturdy&+c iron&+L great helm collects dust here.&n",
     "&+La &+Csturdy &+ciron&+L great helm&n",
      {MEDIUM_IRON_ORE, MEDIUM_IRON_ORE, SMALL_IRON_ORE, SMALL_IRON_ORE,0},
      APPLY_DAMROLL, 1,1,
      APPLY_HITROLL, 1,2,
      20,100,
      ALLOW,
      CLASS_WARRIOR|CLASS_MERCENARY|CLASS_ANTIPALADIN|CLASS_PALADIN|CLASS_BERSERKER|CLASS_RANGER,
      ITEM_WEAR_HEAD,
	0,0,0,0,
  },
{15, "magnificent iron breastplate",
     "&+LA &+Wmagnificent&+c iron&+L breastplate forged by &+W%s&+L lies here.&n",
     "&+La &+Wmagnificent&+c iron&+L breastplate forged by &+W%s&n",
      {LARGE_IRON_ORE, LARGE_IRON_ORE, LARGE_IRON_ORE,MEDIUM_IRON_ORE, 0},
      APPLY_DAMROLL, 1,2,
      APPLY_SAVING_SPELL, -1, -3,
      30,60,
      ALLOW,
      CLASS_WARRIOR|CLASS_PALADIN|CLASS_ANTIPALADIN,
      ITEM_WEAR_BODY,
	0,0,0,0,
  },
{16, "sturdy iron visor",
     "&+LA &+Csturdy&+c iron &+Lvisor has been left here.&n",
     "&+La &+Csturdy&+c iron &+Lvisor&n",
      {MEDIUM_IRON_ORE, SMALL_IRON_ORE,SMALL_IRON_ORE, SMALL_IRON_ORE, 0},
      APPLY_DAMROLL, 1,2,
      APPLY_HITROLL, 1,2,
      20,100,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_EYES,
	0,0,0,0,
  },
{17, "magnificent iron greaves",
     "&+LA set of &+Wmagnificent&+c iron&+L greaves forged by &+W%s&+L have been left here.&n",
     "&+La set of &+Wmagnificent&+c iron&+L greaves forged by &+W%s&n",
      {LARGE_IRON_ORE, LARGE_IRON_ORE,MEDIUM_IRON_ORE, MEDIUM_IRON_ORE,0},
      APPLY_HITROLL, 2,2,
      APPLY_SAVING_SPELL, -1, -2,
      30,60,
      ANTI,
      CLASS_SORCERER|CLASS_CONJURER|CLASS_NECROMANCER|CLASS_ETHERMANCER|CLASS_ILLUSIONIST,
      ITEM_WEAR_LEGS,
	0,0,0,0,
  },
{18, "magnificent iron vambraces",
     "&+LA pair of &+Wmagnificent&+c iron&+L vambraces forged by &+W%s &+Lhave been left here.&n",
     "&+La pair of &+Wmagnificent&+c iron&+L vambraces forged by &+W%s&n",
      {LARGE_IRON_ORE, LARGE_IRON_ORE,MEDIUM_IRON_ORE, MEDIUM_IRON_ORE,0},
      APPLY_DAMROLL, 1,2,
      APPLY_HITROLL, 1,1,
      30,60,
      ANTI,
      CLASS_SORCERER|CLASS_CONJURER|CLASS_NECROMANCER|CLASS_ETHERMANCER|CLASS_ILLUSIONIST,
      ITEM_WEAR_ARMS,
	0,0,0,0,
  },
{19, "magnificent iron sabatons",
     "&+LA pair of &+Wmagnificent&+c iron &+Lsabatons forged by&+W %s &+Lhave been left here.&n",
     "&+La pair of &+Wmagnificent&+c iron&+L sabatons forged by&+W %s&n",
      {LARGE_IRON_ORE, LARGE_IRON_ORE,LARGE_IRON_ORE,0,0},
      APPLY_HITROLL, 1,2,
      APPLY_DAMROLL, 1,1,
      30,60,
      ANTI,
      CLASS_SORCERER|CLASS_CONJURER|CLASS_NECROMANCER|CLASS_ETHERMANCER|CLASS_ILLUSIONIST,
      ITEM_WEAR_FEET,
	0,0,0,0,
  },
{20, "magnificent iron visor",
     "&+LA &+Wmagnificent&+c iron &+Lvisor forged by &+W%s&+L has been dropped here.&n",
     "&+La &+Wmagnificent&+c iron&+L visor forged by &+W%s&n",
      {LARGE_IRON_ORE, LARGE_IRON_ORE,MEDIUM_IRON_ORE,0,0},
      APPLY_HITROLL, 1,2,
      APPLY_SAVING_FEAR, -2, -2,
      30,60,
      ANTI,
      CLASS_SORCERER|CLASS_CONJURER|CLASS_NECROMANCER|CLASS_ETHERMANCER|CLASS_ILLUSIONIST,
ITEM_WEAR_EYES,
	0,0,0,0,
  },
{21, "sturdy iron tail ring",
     "&+LA &+Csturdy&+c iron&+L tail ring has been dropped here.&n",
     "&+La &+Csturdy&+c iron&+L tail ring&n",
      {MEDIUM_IRON_ORE, SMALL_IRON_ORE,0,0,0},
      APPLY_HIT, 2,6,
      APPLY_NONE, 0,0,
      20,100,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_TAIL,
	0,0,0,0,
  },
{22, "sturdy iron knuckles",
     "&+LA pair of &+Csturdy&+c iron&+L knuckles have been dropped here.&n",
     "&+La pair of &+Csturdy&+c iron&+L knuckles&n",
      {MEDIUM_IRON_ORE, MEDIUM_IRON_ORE,SMALL_IRON_ORE,0,0},
      APPLY_HITROLL, 1,3,
      APPLY_NONE, 0,0,
      20,100,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_HANDS,
	0,0,0,0,
  },

{23, "rustic copper gauntlets",
     "&+LSome &+brustic &+ycopper &+Lgauntlets forged by &+W%s &+Llie here.&n",
     "&+Lsome &+brustic &+ycopper &+Lgauntlets&n",
      {MEDIUM_COPPER_ORE, SMALL_COPPER_ORE,0,0,0},
      APPLY_STR, 3,5,
      APPLY_CON, 3,5,
      1,100,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_HANDS,
	0,0,0,0,
  },
{24, "marred iron leggings",
     "some &+rmarred &+ciron leggings forged by &+W%s &+Llie here.&n",
     "some &+rmarred &+ciron leggings&n",
      {SMALL_IRON_ORE, SMALL_IRON_ORE,0,0,0},
      APPLY_MOVE, 6,10,
      APPLY_SAVING_PARA, -1,-2,
      1,100,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_LEGS,
	0,0,0,0,
  },
{25, "shining mithril bracer",
     "A &+Mshining &+mmithril bracer forged by &+W%s &+Llies here.&n",
     "a &+Mshining &+mmithril bracer&n",
      {SMALL_MITHRIL_ORE, 0,0,0,0},
      APPLY_STR, 3,5,
      APPLY_DEX, 3,5,
      1,100,
      ALLOW,
      CLASS_THIEF|CLASS_MERCENARY|CLASS_BARD|CLASS_ASSASSIN,
      ITEM_WEAR_WRIST,
       0,0,0,0,
  },
{26, "simple copper chest plate",
     "A &+bsimple &+ycopper chest plate forged by &+W%s &+Llies here.&n",
     "a &+bsimple &+ycopper chest plate&n",
      {SMALL_COPPER_ORE, SMALL_COPPER_ORE,0,0,0},
      APPLY_HIT, 2,3,
      APPLY_DEX, 2,4,
      1,100,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_BODY,
	0,0,0,0,
  },
{27, "rare gold earring",
     "A &+Brare &+Ygold earring forged by &+W%s &+Llies here.&n",
     "a &+Brare &+Ygold earring&n",
      {MEDIUM_GOLD_ORE, MEDIUM_GOLD_ORE,0,0,0},
      APPLY_HIT, 6,9,
      APPLY_SAVING_PARA, -1,-3,
      1,60,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_EARRING,
	0,0,0,0,
  },
{28, "elegant silver necklace",
     "An &+Gel&+gega&+Gnt &+Csilver ne&+Ccklace forged by &+W%s &+Llies here.&n",
     "an &+Gel&+gega&+Gnt &+Csilver ne&+Ccklace&n",
      {MEDIUM_SILVER_ORE, MEDIUM_SILVER_ORE,0,0,0},
      APPLY_CHA, 4,7,
      APPLY_CON, 6,8,
      10,90,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_NECK,
	0,0,0,0,
  },
{29, "splendid gold boots",
     "A &+Rspl&+ren&+Rdid pair of &+Ygold b&+Yoots forged by &+W%s &+Llies here.&n",
     "a &+Rspl&+ren&+Rdid pair of &+Ygold b&+Yoots&n",
      {SMALL_GOLD_ORE, SMALL_GOLD_ORE,0,0,0},
      APPLY_MOVE, 25,30,
      APPLY_CON, 6,8,
      20,100,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_FEET,
	0,0,0,0,
  },
{30, "marred copper boots",
     "A pair of &+Lmarred &+ycopper b&+yoots forged by &+W%s &+Llie here.&n",
     "a pair of &+Lmarred &+ycopper b&+yoots&n",
      {SMALL_COPPER_ORE, SMALL_COPPER_ORE,0,0,0},
      APPLY_DEX, 1,3,
      APPLY_CON, 1,4,
      20,100,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_FEET,
	0,0,0,0,
  },
{31, "refined platinum gauntlets",
     "A pair of &+mre&+Mfi&+mned &+Cplatinum ga&+Cuntlets forged by &+W%s &+Llie here.&n",
     "a pair of &+mre&+Mfi&+mned &+Cplatinum ga&+Cuntlets&n",
      {MEDIUM_PLATINUM_ORE,MEDIUM_PLATINUM_ORE,SMALL_PLATINUM_ORE,0,0},
      APPLY_HITROLL, 2,4,
      APPLY_AGI, 3,6,
      1,100,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_HANDS,
	0,0,0,0,
  },
{32, "refined platinum bracer",
     "A pair of &+mrefined &+Cplatinum br&+Cacers forged by &+W%s &+Llie here.&n",
     "a pair of &+mrefined &+Cplatinum br&+Cacers&n",
     {MEDIUM_PLATINUM_ORE,MEDIUM_PLATINUM_ORE,SMALL_PLATINUM_ORE,0,0},
      APPLY_HITROLL, 2,4,
      APPLY_AGI, 3,6,
      1,90,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_WRIST,
	0,0,0,0,
  },
{33, "refined platinum crown",
     "A &+mrefined &+Cplatinum cr&+Cown forged by &+W%s &+Llies here.&n",
     "a &+mrefined &+Cplatinum cr&+Cown&n",
      {MEDIUM_PLATINUM_ORE,MEDIUM_PLATINUM_ORE,SMALL_PLATINUM_ORE,0,0},
      APPLY_INT_MAX, 2,4,
      APPLY_AGI, 5,7,
      40,80,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_HEAD,
	0,0,0,0,
  },
{34, "refined platinum chainmail",
     "A &+mrefined &+Cplatinum &+Wchainmail &+wforged by &+W%s &+Llies here.&n",
     "a &+mrefined &+Cplatinum &+Wchainmail&n",
      {MEDIUM_PLATINUM_ORE,MEDIUM_PLATINUM_ORE,SMALL_PLATINUM_ORE,0,0},
      APPLY_INT_MAX, 2,4,
      APPLY_AGI_MAX, 2,5,
      30,100,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_BODY,
	0,0,0,0,
  },
{35, "elegant silver arm guards",
     "Some &+Gelegant &+Csilver &+Lar&+wm guar&+Lds forged by &+W%s &+Llie here.&n",
     "some &+Gelegant &+Csilver &+Lar&+wm guar&+Lds&n",
      {MEDIUM_SILVER_ORE, MEDIUM_SILVER_ORE,0,0,0},
      APPLY_DEX, 7,9,
      APPLY_CON, 6,9,
      10,90,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_ARMS,
	0,0,0,0,
  },
{36, "dainty silver cord",
     "A &+gdainty &+Csilver &+bc&+Bor&+bd forged by &+W%s &+Llies here.&n",
     "a &+gdainty &+Csilver &+bc&+Bor&+bd&n",
      {MEDIUM_SILVER_ORE,SMALL_SILVER_ORE,0,0,0},
      APPLY_SAVING_SPELL, -2,-5,
      APPLY_WIS, 5,8,
      10,100,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_WAIST,
	0,0,0,0,
  },
{37, "mediocre iron knee guards",
     "Some &+Rmediocre &+ciron &+Gkne&+ge guar&+Gds forged by &+W%s &+Llie here.&n",
     "some &+Rmediocre &+ciron &+Gkne&+ge guar&+Gds&n",
      {MEDIUM_SILVER_ORE,SMALL_SILVER_ORE,0,0,0},
      APPLY_SAVING_PARA, -1,-3,
      APPLY_LUCK, 7,9,
      1,100,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_LEGS,
	0,0,0,0,
  },
{38, "mediocre mithril mask",
     "A &+Rmed&+rio&+Rcre &+mmithril &+mm&+Las&+mk forged by &+W%s &+Llies here.&n",
     "a &+Rmed&+rio&+Rcre &+mmithril &+mm&+Las&+mk&n",
      {MEDIUM_MITHRIL_ORE,SMALL_MITHRIL_ORE,0,0,0},
      APPLY_SAVING_FEAR, -1,-3,
      APPLY_LUCK_MAX, 2,5,
      1,90,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_FACE,
	0,AFF2_FIRESHIELD,0,0,
  },
{39, "mediocre mithril platemail",
     "A &+Rmediocre &+mmithril pla&+mtem&starburst forged by &+W%s &+Llies here.&n",
     "a &+Rmediocre &+mmithril pla&+mtem&starburst&n",
      {MEDIUM_MITHRIL_ORE,MEDIUM_MITHRIL_ORE,0,0,0},
      APPLY_SAVING_PARA, -3,-4,
      APPLY_LUCK_MAX, 2,5,
      20,90,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_BODY,
	0,AFF2_FIRESHIELD,0,0,
  },
{40, "mediocre mithril  bracer",
     "A &+Rmed&+rio&+Rcre &+mmithril &+Lbr&+wac&+Ler forged by &+W%s &+Llies here.&n",
     "a &+Rmed&+rio&+Rcre &+mmithril &+Lbr&+wac&+Ler&n",
      {SMALL_MITHRIL_ORE,SMALL_MITHRIL_ORE,SMALL_MITHRIL_ORE,0,0},
      APPLY_HIT, 7,10,
      APPLY_DEX, 5,8,
      20,60,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_WRIST,
	0,AFF2_ULTRAVISION,0,0,
  },
{41, "superior gold bracelet",
     "A &+Bsup&+ber&+Bior &+Ygold br&+Yacelet forged by &+W%s &+Llies here.&n",
     "a &+Bsup&+ber&+Bior &+Ygold br&+Yacelet&n",
      {MEDIUM_GOLD_ORE,MEDIUM_GOLD_ORE,LARGE_GOLD_ORE,0,0},
      APPLY_CON, 4,6,
      APPLY_WIS_MAX, 1,2,
      40,50,
      ALLOW,
      CLASS_CLERIC|CLASS_SHAMAN|CLASS_DRUID,
      ITEM_WEAR_WRIST,
	0,0,0,0,
  },
{42, "superior gold eyelets",
     "A pair of &+Bsup&+ber&+Bior &+Ygold eyelets forged by &+W%s &+Llie here.&n",
     "a pair of &+Bsup&+ber&+Bior &+Ygold eyelets&n",
      {SMALL_GOLD_ORE,MEDIUM_GOLD_ORE,LARGE_GOLD_ORE,0,0},
      APPLY_CON, 2,6,
      APPLY_SAVING_BREATH, -2,-3,
      30,60,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_EYES,
	0,0,0,0,
  },
{43, "superior gold horns",
     "A pair of &+Bsup&+ber&+Bior &+Ygold horns forged by &+W%s &+Llie here.&n",
     "a pair of &+Bsup&+ber&+Bior &+Ygold horns&n",
      {SMALL_GOLD_ORE,MEDIUM_GOLD_ORE,MEDIUM_GOLD_ORE,0,0},
      APPLY_INT, 2,6,
      APPLY_AGI, 4,6,
      30,60,
      ALLOW,
      CLASS_ETHERMANCER|CLASS_SORCERER|CLASS_CONJURER|CLASS_BARD,
      ITEM_WEAR_HORN,
	AFF_PROT_FIRE,0,0,0,
  },
{44, "superior gold bracer",
     "A &+Bsup&+ber&+Bior &+Ygold bracer forged by &+W%s &+Llies here.&n",
     "a &+Bsup&+ber&+Bior &+Ygold bracer&n",
      {SMALL_GOLD_ORE,MEDIUM_GOLD_ORE,MEDIUM_GOLD_ORE,0,0},
      APPLY_INT, 4,6,
      APPLY_FIRE_PROT, 1,1,
      30,60,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_WRIST,
	0,0,0,0,
  },
{45, "superior gold helmet",
     "A &+Bsup&+ber&+Bior &+Ygold helmet forged by &+W%s &+Llies here.&n",
     "a &+Bsup&+ber&+Bior &+Ygold helmet&n",
      {SMALL_GOLD_ORE,MEDIUM_GOLD_ORE,0,0,0},
      APPLY_CON, 5,8,
      APPLY_HIT, 8,10,
      30,60,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_HEAD,
	0,0,0,0,
  },
{46, "superior gold earring",
     "A &+Bsup&+ber&+Bior &+Ygold earring forged by &+W%s &+Llies here.&n",
     "a &+Bsup&+ber&+Bior &+Ygold earring&n",
      {SMALL_GOLD_ORE,MEDIUM_GOLD_ORE,0,0,0},
      APPLY_STR, 4,6,
      APPLY_HIT, 12,15,
      30,60,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_EARRING,
	0,0,0,0,
  },
{47, "superior gold mask",
     "A &+Bsup&+ber&+Bior &+Ygold mask forged by &+W%s &+Llies here.&n",
     "a &+Bsup&+ber&+Bior &+Ygold mask&n",
      {SMALL_GOLD_ORE,0,0,0,0},
      APPLY_DEX, 7,8,
      APPLY_HITROLL, 4,5,
      10,90,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_FACE,
	0,0,0,0,
  },
{48, "damaged mithril gauntlets",
     "A pair of &+Bdamaged &+mmithril gauntlets forged by &+W%s &+Llie here.&n",
     "a pair of &+Bdamaged &+mmithril gauntlets&n",
      {MEDIUM_MITHRIL_ORE,SMALL_MITHRIL_ORE,0,0,0},
      APPLY_LUCK, 7,8,
      APPLY_AGI, 6,8,
      10,90,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_HANDS,
	AFF_WATERBREATH,0,0,0,
  },
{49, "excellent mithril crown",
     "An &+Bexcellent &+mmithril crown forged by &+W%s &+Llies here.&n",
     "an &+Bexcellent &+mmithril crown&n",
      {MEDIUM_MITHRIL_ORE,MEDIUM_MITHRIL_ORE,0,0,0},
      APPLY_CON_MAX, 2,3,
      APPLY_SAVING_BREATH, -2,-3,
      20,70,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_HEAD,
	AFF_AWARE,0,0,0,
  },
{50, "excellent mithril belt",
     "An &+Bexcellent &+mmithril belt forged by &+W%s &+Llies here.&n",
     "an &+Bexcellent &+mmithril belt&n",
      {MEDIUM_MITHRIL_ORE,MEDIUM_MITHRIL_ORE,0,0,0},
      APPLY_AGI, 5,7,
      APPLY_HITROLL, 1,3,
      30,80,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_WAIST,
	0,0,AFF3_COLDSHIELD,0,
  },
{51, "amazing mithril boots",
     "Some &+Gamazing &+mmithril boots forged by &+W%s &+Llie here.&n",
     "some &+Gamazing &+mmithril boots&n",
      {MEDIUM_MITHRIL_ORE,MEDIUM_MITHRIL_ORE,SMALL_MITHRIL_ORE,0,0},
      APPLY_DAMROLL, 1,2,
      APPLY_HIT, 10,15,
      30,80,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_FEET,
	0,0,AFF3_COLDSHIELD,0,
  },
{52, "godly mithril boots",
     "Some &+mgodly &+mmithril boots forged by &+W%s &+Llie here.&n",
     "some &+mgodly &+mmithril boots&n",
      {MEDIUM_MITHRIL_ORE,MEDIUM_MITHRIL_ORE,SMALL_MITHRIL_ORE,0,0},
      APPLY_HITROLL, 3,5,
      APPLY_INT, 4,5,
      60,50,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_FEET,
	0,0,0,0,
  },
{53, "holy mithril chainmail suit",
     "A &+Yholy &+mmithril chainmail suit forged by &+W%s &+Llies here.&n",
     "a &+Yholy &+mmithril chainmail suit&n",
      {MEDIUM_MITHRIL_ORE,MEDIUM_MITHRIL_ORE,SMALL_MITHRIL_ORE,0,0},
      APPLY_WIS_MAX, 3,4,
      APPLY_AGI_MAX, 2,3,
      30,60,
      ALLOW,
      CLASS_CLERIC|CLASS_SHAMAN|CLASS_DRUID|CLASS_ETHERMANCER,
      ITEM_WEAR_BODY,
	AFF_FLY,0,0,0,
  },
{54, "holy mithril gauntlets",
     "A pair of &+Yholy &+mmithril gauntlets forged by &+W%s &+Llie here.&n",
     "a pair of &+Yholy &+mmithril gauntlets&n",
      {MEDIUM_MITHRIL_ORE,MEDIUM_MITHRIL_ORE,SMALL_MITHRIL_ORE,0,0},
      APPLY_HITROLL, 3,4,
      APPLY_DAMROLL, 2,3,
      30,30,
      ALLOW,
      CLASS_PALADIN|CLASS_RANGER|CLASS_CLERIC,
      ITEM_WEAR_HANDS,
	AFF_FLY,0,0,0,
  },
{55, "holy mithril greaves",
     "A pair of &+Yholy &+mmithril greaves forged by &+W%s &+Llie here.&n",
     "a pair of &+Yholy &+mmithril greaves&n",
      {MEDIUM_MITHRIL_ORE,SMALL_MITHRIL_ORE,SMALL_MITHRIL_ORE,0,0},
      APPLY_HITROLL, 2,3,
      APPLY_DAMROLL, 1,2,
      30,30,
      ALLOW,
      CLASS_PALADIN|CLASS_RANGER|CLASS_CLERIC,
      ITEM_WEAR_LEGS,
	AFF_WATERBREATH,0,0,0,
  },
{56, "holy mithril leggings",
     "A pair of &+Yholy &+mmithril leggings forged by &+W%s &+Llie here.&n",
     "a pair of &+Yholy &+mmithril leggings&n",
      {MEDIUM_MITHRIL_ORE,MEDIUM_MITHRIL_ORE,SMALL_MITHRIL_ORE,0,0},
      APPLY_WIS_MAX, 1,3,
      APPLY_SAVING_SPELL, -1,-2,
      30,30,
      ALLOW,
      CLASS_PALADIN|CLASS_RANGER|CLASS_CLERIC,
      ITEM_WEAR_LEGS,
	0,0,0,0,
  },
{57, "unholy mithril gauntlets",
     "A pair of &+runholy &+mmithril gauntlets forged by &+W%s &+Llie here.&n",
     "a pair of &+runholy &+mmithril gauntlets&n",
      {MEDIUM_MITHRIL_ORE,MEDIUM_MITHRIL_ORE,SMALL_MITHRIL_ORE,0,0},
      APPLY_HITROLL, 2,4,
      APPLY_DAMROLL, 2,3,
      30,30,
      ALLOW,
      CLASS_BERSERKER|CLASS_ANTIPALADIN|CLASS_CLERIC,
      ITEM_WEAR_HANDS,
	0,0,0,0,
  },
{58, "unholy mithril platemail",
     "An &+runholy &+mmithril &+Lplat&+wema&+Lil forged by &+W%s &+Llies here.&n",
     "an &+runholy &+mmithril &+Lplat&+wema&+Lil&n",
      {MEDIUM_MITHRIL_ORE,MEDIUM_MITHRIL_ORE,SMALL_MITHRIL_ORE,0,0},
      APPLY_HITROLL, 3,4,
      APPLY_DAMROLL, 2,3,
      30,30,
      ALLOW,
      CLASS_ANTIPALADIN|CLASS_RANGER|CLASS_CLERIC,
      ITEM_WEAR_BODY,
	0,0,0,0,
  },
{59, "unholy mithril leggings",
     "A pair of &+runholy &+mmithril leggings forged by &+W%s &+Llie here.&n",
     "a pair of &+runholy &+mmithril leggings&n",
      {MEDIUM_MITHRIL_ORE,MEDIUM_MITHRIL_ORE,SMALL_MITHRIL_ORE,0,0},
      APPLY_WIS_MAX, 1,3,
      APPLY_SAVING_SPELL, -2,-3,
      30,30,
      ALLOW,
      CLASS_ANTIPALADIN|CLASS_CLERIC,
      ITEM_WEAR_LEGS,
	AFF_FLY,0,0,0,
  },
{60, "crafty copper crown",
     "A &+Mcrafty &+ycopper crown forged by &+W%s &+Llies here.&n",
     "a &+Mcrafty &+ycopper crown&n",
      {SMALL_COPPER_ORE,0,0,0,0},
      APPLY_LUCK, 3,5,
      APPLY_SAVING_FEAR, -2,-3,
      1,100,
      ALLOW,
      CLASS_ALCHEMIST,
      ITEM_WEAR_HEAD,
	0,0,0,0,
  },
{61, "crafty iron crown",
     "A &+Mcrafty &+ciron crown forged by &+W%s &+Llies here.&n",
     "a &+Mcrafty &+ciron crown&n",
      {SMALL_IRON_ORE,0,0,0,0},
      APPLY_LUCK, 5,6,
      APPLY_LUCK_MAX, 3,4,
      20,80,
      ALLOW,
      CLASS_ALCHEMIST,
      ITEM_WEAR_HEAD,
	0,0,0,0,
  },
{62, "gothic iron circlet",
     "A &+Lgo&+wth&+Lic &+ciron &+Bci&+brcl&+Bet forged by &+W%s &+Llies here.&n",
     "a &+Lgo&+wth&+Lic &+ciron &+Bci&+brcl&+Bet&n",
      {SMALL_IRON_ORE,MEDIUM_IRON_ORE,0,0,0},
      APPLY_CHA, 2,4,
      APPLY_SAVING_SPELL, -2,-3,
      30,80,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_HEAD,
	0,0,0,0,
  },
{63, "gothic iron gauntlets",
     "Some &+Lgo&+wth&+Lic &+ciron &+Bgau&+bntl&+Bets forged by &+W%s &+Llie here.&n",
     "some &+Lgo&+wth&+Lic &+ciron &+Bgau&+bntl&+Bets&n",
      {SMALL_IRON_ORE,MEDIUM_IRON_ORE,0,0,0},
      APPLY_HITROLL, 1,2,
      APPLY_SAVING_SPELL, -2,-3,
      30,80,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_HANDS,
	0,0,0,0,
  },
{64, "gothic iron boots",
     "Some &+Lgo&+wth&+Lic &+ciron &+Bb&+boots forged by &+W%s &+Llie here.&n",
     "some &+Lgo&+wth&+Lic &+ciron &+Bb&+boots&n",
      {SMALL_IRON_ORE,MEDIUM_IRON_ORE,MEDIUM_IRON_ORE,0,0},
      APPLY_HIT, 5,7,
      APPLY_MOVE, 8,10,
      40,70,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_FEET,
	0,0,0,0,
  },
{65, "gothic iron facemask",
     "A &+Lgo&+wth&+Lic &+ciron &+Bfa&+bcema&+Bsk forged by &+W%s &+Llies here.&n",
     "a &+Lgo&+wth&+Lic &+ciron &+Bfa&+bcema&+Bsk&n",
      {SMALL_IRON_ORE,0,0,0,0},
      APPLY_HIT, 5,8,
      APPLY_SAVING_SPELL, -1,-2,
      1,90,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_FACE,
	0,0,0,0,
  },
{66, "gothic copper facemask",
     "A &+Lgo&+wth&+Lic &+ycopper &+Bfa&+bcema&+Bsk forged by &+W%s &+Llies here.&n",
     "a &+Lgo&+wth&+Lic &+ycopper &+Bfa&+bcema&+Bsk&n",
      {SMALL_COPPER_ORE,LARGE_COPPER_ORE,0,0,0},
      APPLY_HIT, 8,10,
      APPLY_SAVING_SPELL, -1,-3,
      1,80,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_FACE,
	0,0,0,0,
  },
{67, "gothic copper boots",
     "Some &+Lgo&+wth&+Lic &+ycopper &+Bb&+boots forged by &+W%s &+Llie here.&n",
     "some &+Lgo&+wth&+Lic &+ycopper &+Bb&+boots&n",
      {SMALL_COPPER_ORE,MEDIUM_COPPER_ORE,MEDIUM_COPPER_ORE,0,0},
      APPLY_HIT, 7,10,
      APPLY_MOVE, 12,15,
      40,60,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_FEET,
	0,0,0,0,
  },
{68, "gothic copper gauntlets",
     "Some &+Lgo&+wth&+Lic &+ycopper &+Bgau&+bntl&+Bets forged by &+W%s &+Llie here.&n",
     "some &+Lgo&+wth&+Lic &+ycopper &+Bgau&+bntl&+Bets&n",
      {SMALL_COPPER_ORE,MEDIUM_COPPER_ORE,0,0,0},
      APPLY_HITROLL, 2,3,
      APPLY_SAVING_SPELL, -2,-3,
      30,60,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_HANDS,
	0,0,0,0,
  },
{69, "gothic copper circlet",
     "A &+Lgo&+wth&+Lic &+ycopper &+Bci&+brcl&+Bet forged by &+W%s &+Llies here.&n",
     "a &+Lgo&+wth&+Lic &+ycopper &+Bci&+brcl&+Bet&n",
      {SMALL_COPPER_ORE,MEDIUM_COPPER_ORE,0,0,0},
      APPLY_CHA, 6,8,
      APPLY_SAVING_SPELL, -2,-3,
      30,60,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_HEAD,
	0,0,0,0,
  },
{70, "inlaid copper robe",
     "A &+ycopper &+Yinlaid &+Lrobe forged by &+W%s &+Llies here.&n",
     "a &+ycopper &+Yinlaid &+Lrobe&n",
      {SMALL_COPPER_ORE,0,0,0,0},
      APPLY_DEX, 3,4,
      APPLY_DAMROLL, 1,2,
      1,100,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_BODY,
	0,0,0,0,
  },
{71, "embossed copper crown",
     "An &+Lembo&+css&+Led &+ycopper &+Lcrown forged by &+W%s &+Llies here.&n",
     "an &+Lembo&+css&+Led &+ycopper &+Lcrown&n",
      {SMALL_COPPER_ORE,SMALL_COPPER_ORE,MEDIUM_COPPER_ORE,0,0},
      APPLY_SAVING_SPELL, -2,-3,
      APPLY_HIT,8,14,
      1,100,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_HEAD,
	0,0,0,0,
  },
{72, "embossed copper bracelet",
     "An &+Lembo&+css&+Led &+ycopper &+Bb&+bracelet forged by &+W%s &+Llies here.&n",
     "an &+Lembo&+css&+Led &+ycopper &+Bb&+bracelet&n",
      {SMALL_COPPER_ORE,SMALL_COPPER_ORE,0,0,0},
      APPLY_CON,3,5,
      APPLY_STR,3,5,
      1,100,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_WRIST,
	0,0,0,0,
  },
{73, "embossed copper bracer",
     "An &+Lembo&+css&+Led &+ycopper &+Lbracer forged by &+W%s &+Llies here.&n",
     "an &+Lembo&+css&+Led &+ycopper &+Lbracer&n",
      {SMALL_COPPER_ORE,SMALL_COPPER_ORE,MEDIUM_COPPER_ORE,0,0},
      APPLY_SAVING_SPELL, -2,-3,
      APPLY_HIT,6,8,
      1,100,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_WRIST,
	0,0,0,0,
  },
{74, "embossed copper boots",
     "A pair of &+Lembo&+css&+Led &+ycopper &+Bb&+boots forged by &+W%s &+Llie here.&n",
     "a pair of &+Lembo&+css&+Led &+ycopper &+Bb&+boots&n",
      {SMALL_COPPER_ORE,SMALL_COPPER_ORE,MEDIUM_COPPER_ORE,0,0},
      APPLY_SAVING_PARA, -2,-3,
      APPLY_MOVE,12,15,
      1,100,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_FEET,
	0,0,0,0,
  },
{75, "embossed copper necklace",
     "An &+Lembo&+css&+Led &+ycopper &+Bn&+becklace forged by &+W%s &+Llies here.&n",
     "an &+Lembo&+css&+Led &+ycopper &+Bn&+becklace&n",
      {SMALL_COPPER_ORE,0,0,0,0},
      APPLY_DEX, 4,5,
      APPLY_CHA,7,8,
      1,100,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_NECK,
	0,0,0,0,
  },
{76, "gothic silver cord",
     "A &+Lgo&+wth&+Lic &+wsilver &+Bc&+bor&+Bd forged by &+W%s &+Llies here.&n",
     "a &+Lgo&+wth&+Lic &+wsilver &+Bc&+bor&+Bd&n",
      {SMALL_SILVER_ORE,0,0,0,0},
      APPLY_CON, 4,5,
      APPLY_DAMROLL,1,2,
      1,100,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_NECK,
	0,0,0,0,
  },
{77, "gothic silver necklace",
     "A &+Lgo&+wth&+Lic &+wsilver &+Bn&+becklace forged by &+W%s &+Llies here.&n",
     "a &+Lgo&+wth&+Lic &+wsilver &+Bn&+becklace&n",
      {LARGE_SILVER_ORE,LARGE_SILVER_ORE,0,0,0},
      APPLY_CON, 8,9,
      APPLY_AGI,8,9,
      20,80,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_NECK,
	0,0,0,0,
  },
{78, "gothic silver bracer",
     "A &+Lgo&+wth&+Lic &+wsilver &+Bb&+bracer forged by &+W%s &+Llies here.&n",
     "a &+Lgo&+wth&+Lic &+wsilver &+Bb&+bracer&n",
      {LARGE_SILVER_ORE,LARGE_SILVER_ORE,LARGE_SILVER_ORE,0,0},
      APPLY_HITROLL, 1,3,
      APPLY_DAMROLL,2,2,
      40,50,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_WRIST,
	0,0,0,0,
  },
{79, "gothic silver mask",
     "A &+Lgo&+wth&+Lic &+wsilver &+Bm&+bask forged by &+W%s &+Llies here.&n",
     "a &+Lgo&+wth&+Lic &+wsilver &+Bm&+bask&n",
      {LARGE_SILVER_ORE,LARGE_SILVER_ORE,LARGE_SILVER_ORE,0,0},
      APPLY_CON, 5,7,
      APPLY_SAVING_BREATH,-2,-3,
      40,50,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_FACE,
	0,0,0,0,
  },
{80, "gothic silver circlet",
     "A &+Lgo&+wth&+Lic &+wsilver &+Bc&+birclet forged by &+W%s &+Llies here.&n",
     "a &+Lgo&+wth&+Lic &+wsilver &+Bc&+birclet&n",
      {LARGE_SILVER_ORE,LARGE_SILVER_ORE,LARGE_SILVER_ORE,LARGE_SILVER_ORE,0},
      APPLY_HIT, 12,15,
      APPLY_INT_MAX,2,3,
      60,50,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_HEAD,
	0,0,0,0,
  },
{81, "chaotic mithril leg plates",
     "Some &+rcha&+Ro&+rtic &+mmithril &+Gleg plates forged by &+W%s &+Llie here.&n",
     "some &+rcha&+Ro&+rtic &+mmithril &+Gleg plates&n",
      {LARGE_MITHRIL_ORE,LARGE_MITHRIL_ORE,MEDIUM_MITHRIL_ORE,0,0},
      APPLY_HITROLL, 3,4,
      APPLY_DEX_MAX,2,3,
      40,50,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_LEGS,
	0,0,0,0,
  },
{82, "chaotic mithril chainmail",
     "A &+rcha&+Ro&+rtic &+mmithril &+Lcha&+rinm&+Lail forged by &+W%s &+Llies here.&n",
     "a &+rcha&+Ro&+rtic &+mmithril &+Lcha&+rinm&+Lail&n",
      {LARGE_MITHRIL_ORE,LARGE_MITHRIL_ORE,MEDIUM_MITHRIL_ORE,0,0}, 
      APPLY_HIT, 23,25,
      APPLY_WIS_MAX,2,4,
      70,70,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_BODY,
	0,0,0,0,
  },
{83, "chaotic platinum band",
     "A &+rcha&+Ro&+rtic &+Wplatinum &+Lband forged by &+W%s &+Llies here.&n",
     "a &+rcha&+Ro&+rtic &+Wplatinum &+Lband&n",
      {SMALL_PLATINUM_ORE,SMALL_PLATINUM_ORE,MEDIUM_PLATINUM_ORE,0,0},
      APPLY_HIT, 13,15,
      APPLY_AGI_MAX,3,4,
      40,70,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_FINGER,
	0,0,0,0,
  },
{84, "chaotic platinum visor",
     "A &+rcha&+Ro&+rtic &+Wplatinum &+Lvisor forged by &+W%s &+Llies here.&n",
     "a &+rcha&+Ro&+rtic &+Wplatinum &+Lvisor&n",
      {SMALL_PLATINUM_ORE,SMALL_PLATINUM_ORE,MEDIUM_PLATINUM_ORE,0,0},
      APPLY_CHA, 6,8,
      APPLY_AGI_MAX,2,3,
      40,70,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_EYES,
	AFF_WATERBREATH,0,0,0,
  },
{85, "chaotic platinum leggings",
     "Some &+rcha&+Ro&+rtic &+Wplatinum &+Lleggings forged by &+W%s &+Llie here.&n",
     "some &+rcha&+Ro&+rtic &+Wplatinum &+Lleggings&n",
      {SMALL_PLATINUM_ORE,SMALL_PLATINUM_ORE,MEDIUM_PLATINUM_ORE,0,0},
      APPLY_AGI, 11,12,
      APPLY_STR_MAX,1,2,
      40,70,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_LEGS,
	AFF_WATERBREATH,0,0,0,
  },
{86, "chaotic platinum sash",
     "A &+rcha&+Ro&+rtic &+Wplatinum &+Lsash forged by &+W%s &+Llies here.&n",
     "a &+rcha&+Ro&+rtic &+Wplatinum &+Lsash&n",
      {SMALL_PLATINUM_ORE,SMALL_PLATINUM_ORE,MEDIUM_PLATINUM_ORE,0,0},
      APPLY_DEX, 10,12,
      APPLY_STR,1,2,
      40,70,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_WAIST,
	AFF_WATERBREATH,0,0,0,
  },
{87, "chaotic platinum shield",
     "A &+rcha&+Ro&+rtic &+Wplatinum &+Lshield forged by &+W%s &+Llies here.&n",
     "a &+rcha&+Ro&+rtic &+Wplatinum &+Lshield&n",
      {SMALL_PLATINUM_ORE,SMALL_PLATINUM_ORE,MEDIUM_PLATINUM_ORE,0,0},
      APPLY_DAMROLL, 1,2,
      APPLY_STR_MAX,1,3,
      40,50,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_SHIELD,
	AFF_WATERBREATH,0,0,0,
  },
{88, "exquisite silver earring starburst",
     "An &+Cex&+cquisi&+Cte &+wsilver &+Lea&+wrr&+Ling with a &+ygo&+Yld&+yen starburst forged by &+W%s &+Llies here.&n",
     "an &+Cex&+cquisi&+Cte &+wsilver &+Lea&+wrr&+Ling with a &+ygo&+Yld&+yen starburst&n",
      {MEDIUM_SILVER_ORE,SMALL_GOLD_ORE,0,0,0},
      APPLY_CHA, 7,8,
      APPLY_SAVING_FEAR,-1,-2,
      40,50,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_EARRING,
	0,0,0,0,
  },
{89, "exquisite golden earring starburst",
     "An &+Cex&+cquisi&+Cte &+Ygolden &+Lea&+wrr&+Ling with a &+Wplatinum &+ystarburst forged by &+W%s &+Llies here.&n",
     "an &+Cex&+cquisi&+Cte &+Ygolden &+Lea&+wrr&+Ling with a &+Wplatinum &+ystarburst&n",
      {MEDIUM_GOLD_ORE,SMALL_PLATINUM_ORE,0,0,0},
      APPLY_CHA, 10,11,
      APPLY_SAVING_FEAR,-2,-3,
      60,80,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_EARRING,
	0,0,0,0,
  },
{90, "simple golden earring starburst",
     "A &+Rs&+rimpl&+Re &+Wplatinum &+Lea&+wrr&+Ling with a &+mmithril &+ystarburst forged by &+W%s &+Llies here.&n",
     "a &+Rs&+rimpl&+Re &+Wplatinum &+Lea&+wrr&+Ling with a &+mmithril &+ystarburst&n",
      {MEDIUM_GOLD_ORE,SMALL_MITHRIL_ORE,0,0,0},
      APPLY_CHA_MAX, 2,3,
      APPLY_SAVING_FEAR,-2,-3,
      60,80,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_EARRING,
      AFF_FARSEE,0,0,0,
  },
{91, "exquisite golden earring",
     "An &+Cex&+cquisi&+Cte &+mmithril &+Lea&+wrr&+Ling forged by &+W%s &+Llies here.&n",
     "an &+Cex&+cquisi&+Cte &+mmithril &+Lea&+wrr&+Ling&n",
      {MEDIUM_MITHRIL_ORE,0,0,0,0},
      APPLY_CHA_MAX, 3,4,
      APPLY_SAVING_FEAR,-2,-3,
      60,80,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_EARRING,
	AFF_FARSEE,0,0,0,
  },
{92, "clover leaf copper earring",
     "A &+gcl&+Gov&+ger &+Gleaf &+ycopper &+Lea&+wrr&+Ling forged by &+W%s &+Llies here.&n",
     "a &+gcl&+Gov&+ger &+Gleaf &+ycopper &+Lea&+wrr&+Ling&n",
      {SMALL_COPPER_ORE,0,0,0,0},
      APPLY_LUCK, 3,4,
      APPLY_SAVING_PARA,-1,-1,
      60,80,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_EARRING,
	0,0,0,0,
  },
{93, "clover leaf silver earring",
     "A &+gcl&+Gov&+ger &+Gleaf &+wsilver &+Lea&+wrr&+Ling forged by &+W%s &+Llies here.&n",
     "a &+gcl&+Gov&+ger &+Gleaf &+wsilver &+Lea&+wrr&+Ling&n",
      {SMALL_SILVER_ORE,0,0,0,0},
      APPLY_LUCK, 4,5,
      APPLY_SAVING_PARA,-1,-1,
      60,80,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_EARRING,
	0,0,0,0,
  },
{94, "clover leaf golden earring",
     "A &+gcl&+Gov&+ger &+Gleaf &+Ygolden &+Lea&+wrr&+Ling forged by &+W%s &+Llies here.&n",
     "a &+gcl&+Gov&+ger &+Gleaf &+Ygolden &+Lea&+wrr&+Ling&n",
      {SMALL_GOLD_ORE,0,0,0,0},
      APPLY_LUCK_MAX, 2,3,
      APPLY_SAVING_PARA,-2,-3,
      60,80,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_EARRING,
	0,0,0,0,
  },
{95, "clover leaf platinum earring",
     "A &+gcl&+Gov&+ger &+Gleaf &+Wplatinum &+Lea&+wrr&+Ling forged by &+W%s &+Llies here.&n",
     "a &+gcl&+Gov&+ger &+Gleaf &+Wplatinum &+Lea&+wrr&+Ling&n",
      {SMALL_PLATINUM_ORE,SMALL_PLATINUM_ORE,0,0,0},
      APPLY_LUCK_MAX, 2,3,
      APPLY_HIT,8,10,
      60,80,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_EARRING,
	0,0,0,0,
  },
{96, "clover leaf mithril earring",
     "A &+gcl&+Gov&+ger &+Gleaf &+mmithril &+Lea&+wrr&+Ling forged by &+W%s &+Llies here.&n",
     "a &+gcl&+Gov&+ger &+Gleaf &+mmithril &+Lea&+wrr&+Ling&n",
      {SMALL_MITHRIL_ORE,SMALL_MITHRIL_ORE,0,0,0},
      APPLY_LUCK_MAX, 4,5,
      APPLY_HIT,13,15,
      60,80,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_EARRING,
	AFF_AWARE,0,0,0,
  },
{97, "hammered iron leg plates",
     "Some &+rha&+Rmm&+rered &+ciron &+yleg pl&+Late&+ys forged by &+W%s &+Llies here.&n",
     "some &+rha&+Rmm&+rered &+ciron &+yleg pl&+Late&+ys&n",
      {SMALL_IRON_ORE,MEDIUM_IRON_ORE,MEDIUM_IRON_ORE,0,0},
      APPLY_CON, 4,5,
      APPLY_HIT,7,8,
      20,100,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_LEGS,
	0,0,0,0,
  },
{98, "irridescent square shield of mithril",
     "An &+Cirr&+wide&+Cs&+cc&+Cent &+bsquare &+Bsh&+bie&+Bld of &+mmithril forged by &+W%s &+Llies here.&n",
     "an &+Cirr&+wide&+Cs&+cc&+Cent &+bsquare &+Bsh&+bie&+Bld of &+mmithril&n",
      {MEDIUM_MITHRIL_ORE,LARGE_MITHRIL_ORE,LARGE_MITHRIL_ORE,0,0},
      APPLY_CON_MAX, 2,3,
      APPLY_DEX_MAX,1,2,
      20,100,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_SHIELD,
	AFF_AWARE,0,0,0,
  },
{99, "irridescent mask of hammered mithril",
     "An &+Cirr&+wide&+Cs&+cc&+Cent &+Bm&+bas&+Bk of &+rha&+Rmm&+Rered &+mmithril forged by &+W%s &+Llies here.&n",
     "an &+Cirr&+wide&+Cs&+cc&+Cent &+Bm&+bas&+Bk of &+rha&+Rmm&+Rered &+mmithril&n",
      {SMALL_MITHRIL_ORE,SMALL_MITHRIL_ORE,MEDIUM_MITHRIL_ORE,MEDIUM_MITHRIL_ORE,0},
      APPLY_WIS_MAX, 2,3,
      APPLY_DEX,4,6,
      20,100,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_FACE,
	AFF_FARSEE,0,0,0,
  },
{100, "elaborate chain of platinum and silver",
     "An &+Bel&+babo&+Brate &+Cch&+cai&+Cn of &+Wplatinum and &+wsilver forged by &+W%s &+Llies here.&n",
     "an &+Bel&+babo&+Brate &+Cch&+cai&+Cn of &+Wplatinum and &+wsilver&n",
      {MEDIUM_PLATINUM_ORE,MEDIUM_SILVER_ORE,0,0,0},
      APPLY_CHA, 6,8,
      APPLY_AGI,6,8,
      20,100,
      ANTI,
      CLASS_NONE,
      ITEM_WEAR_WAIST,
	0,0,0,0,
  },
{101, "hammered copper breastplate",
      "A &+Lha&+wmm&+Lered &+ycopper &+Wbre&+wastpl&+Wate forged by &+W%s &+Llies here.&n",
      "a &+Lha&+wmm&+Lered &+ycopper &+Wbre&+wastpl&+Wate&n",
       {MEDIUM_COPPER_ORE,LARGE_COPPER_ORE,LARGE_COPPER_ORE,0,0},
       APPLY_CON, 5,6,
       APPLY_HIT,7,9,
       20,100,
       ANTI,
       CLASS_NONE,
       ITEM_WEAR_BODY,
        0,0,0,0,
  },
{102, "hammered silver breastplate",
      "A &+Lha&+wmm&+Lered &+wsilver &+Wbre&+wastpl&+Wate forged by &+W%s &+Llies here.&n",
      "a &+Lha&+wmm&+Lered &+wsilver &+Wbre&+wastpl&+Wate&n",
       {MEDIUM_SILVER_ORE,LARGE_SILVER_ORE,LARGE_SILVER_ORE,0,0},
       APPLY_CON, 5,6,
       APPLY_HIT,13,15,
       20,100,
       ANTI,
       CLASS_NONE,
       ITEM_WEAR_BODY,
    	0,0,0,0,
  },
{103, "exquisite chain mithril platinum",
      "An &+Cex&+cquisi&+Cte &+Wch&+Wai&+wn of &+mmithril with &+Wplatinum and &+wsilver &+Cl&+cin&+Cks &+Llies here.&n",
      "an &+Cex&+cquisi&+Cte &+Wch&+Wai&+wn of &+mmithril with &+Wplatinum and &+wsilver &+Cl&+cin&+Cks&n",
       {MEDIUM_SILVER_ORE,LARGE_MITHRIL_ORE,MEDIUM_PLATINUM_ORE,0,0},
       APPLY_INT_MAX, 1,2,
       APPLY_HIT,13,15,
       60,60,
       ANTI,
       CLASS_NONE,
       ITEM_WEAR_WAIST,
      	0,0,0,0,
  },
{104, "irridescent mithril copper leggings",
      "A pair of &+Cirr&+wide&+Cs&+cc&+Cent &+mmithril &+Ll&+wegg&+Lings with &+ycopper &+Lde&+ytai&+Lls &+Llie here.&n",
      "a pair of &+Cirr&+wide&+Cs&+cc&+Cent &+mmithril &+Ll&+wegg&+Lings with &+ycopper &+Lde&+ytai&+Lls&n",
       {MEDIUM_SILVER_ORE,LARGE_MITHRIL_ORE,MEDIUM_PLATINUM_ORE,0,0},
       APPLY_MOVE, 27,30,
       APPLY_DEX,3,4,
       20,90,
       ANTI,
       CLASS_NONE,
       ITEM_WEAR_LEGS,
     	0,0,0,0,
  },
{105, "irridescent mithril torque",
      "An &+Cirr&+wide&+Cs&+cc&+Cent &+mmithril &+Lto&+wrqu&+Le forged by &+W%s &+Llies here.&n",
      "an &+Cirr&+wide&+Cs&+cc&+Cent &+mmithril &+Lto&+wrqu&+Le&n",
       {MEDIUM_MITHRIL_ORE,SMALL_MITHRIL_ORE,0,0,0},
       APPLY_HIT, 2,3,
       APPLY_DEX,4,5,
       20,90,
       ANTI,
       CLASS_NONE,
       ITEM_WEAR_NECK,
        0,AFF2_ULTRAVISION,0,0,
  },
{106, "platinum electrum chainmail",
      "&+WA suit  of &+Ll&+Wi&+Ln&+Wk&+Le&+Wd &+Wplatinum and &+Celectrum &+Wrings &+Llies here.&n",
      "&+Wa suit of &+Ll&+Wi&+Ln&+Wk&+Le&+Wd &+Wplatinum and &+Celectrum &+Wrings&n",
       {MEDIUM_PLATINUM_ORE,SMALL_SILVER_ORE,LARGE_GOLD_ORE,0,0},
       APPLY_CON_MAX, 4,5,
       APPLY_DEX,-5,-6,
       20,90,
       ANTI,
       CLASS_NONE,
       ITEM_WEAR_BODY,
       	0,0,0,0,
},
{107, "glowing copper clogs",
      "A &+Rpair of small &+Ygl&+Wow&+Ying &+ycopper &+Bc&+blog&+Bs forged by &+W%s &+Llie here.&n",
      "a &+Rpair of small &+Ygl&+Wow&+Ying &+ycopper &+Bc&+blog&+Bs&n",
       {MEDIUM_COPPER_ORE,SMALL_COPPER_ORE,0,0,0},
       APPLY_MOVE, 18,20,
       APPLY_CON,3,5,
       20,90,
       ANTI,
       CLASS_NONE,
       ITEM_WEAR_FEET,
        0,0,0,0,
},
{108, "tiny platinum stud glowing power",
      "&+wA tiny &+Wplatinum &+ystud &+Cglowing &+wwith raw &+Rp&+ro&+Rw&+re&+Rr&+w forged by &+W%s &+Llies here.&n",
      "&+wa tiny &+Wplatinum &+ystud &+Cglowing &+wwith raw &+Rp&+ro&+Rw&+re&+Rr&+w&n",
       {MEDIUM_PLATINUM_ORE,SMALL_PLATINUM_ORE,0,0,0},
       APPLY_POW, 8,10,
       APPLY_POW_MAX,2,4,
       20,90,
       ANTI,
       CLASS_NONE,
       ITEM_WEAR_EARRING,
      	0,0,0,0,
},
{109, "evil iron war helm",
      "An &+re&+Rv&+ri&+Rl &+ciron &+rwar helm &+wwith &+rnasty sp&+Lik&+res&+w forged by &+W%s &+Llies here.&n",
      "an &+re&+Rv&+ri&+Rl &+ciron &+rwar helm &+wwith &+rnasty sp&+Lik&+res&+w&n",
       {SMALL_IRON_ORE,MEDIUM_IRON_ORE,LARGE_IRON_ORE,0,0},
       APPLY_STR, 4,5,
       APPLY_SAVING_SPELL,-1,-2,
       20,90,
       ANTI,
       CLASS_NONE,
       ITEM_WEAR_HEAD,
        0,0,0,0,
},
{110, "beautiful mithril eyeglasses",
      "A &+wb&+Ce&+wa&+Cut&+wi&+Cfu&+wl &+wpair of &+mmithril &+we&+Cy&+We&+wg&+Cl&+Wa&+ws&+Cs&+We&+ws forged by &+W%s &+Llies here.&n",
      "a &+wb&+Ce&+wa&+Cut&+wi&+Cfu&+wl &+wpair of &+mmithril &+we&+Cy&+We&+wg&+Cl&+Wa&+ws&+Cs&+We&+ws&n",
       {SMALL_MITHRIL_ORE,MEDIUM_MITHRIL_ORE,0,0,0},
       APPLY_INT_MAX, 2,3,
       APPLY_CHA,4,6,
       50,50,
       ANTI,
       CLASS_NONE,
       ITEM_WEAR_EYES,
        0,AFF2_ULTRAVISION,0,0,
  },
{111, "pretty gold earring heart",
      "A pretty &+Ygold &+mea&+Mrr&+ming &+win the shape of a &+R<3&+w forged by &+W%s &+Llies here.&n",
      "a &+Mv&+mer&+My pretty &+Ygold &+mea&+Mrr&+ming &+win the shape of a &+R<3&+w&n",
       {SMALL_GOLD_ORE,SMALL_GOLD_ORE,0,0,0},
       APPLY_LUCK, 8,10,
       APPLY_CHA,8,10,
       50,50,
       ANTI,
       CLASS_NONE,
       ITEM_WEAR_EARRING,
       	0,0,0,0,
  },
{112, "evil gold skull shaped earring",
      "An &+Re&+rv&+Ri&+rl &+Ygold &+Lsk&+Yu&+Lll&+Y-&+Lsh&+Yap&+Led ea&+Yrri&+Lng&+w forged by &+W%s &+Llies here.&n",
      "an &+Re&+rv&+Ri&+rl &+Ygold &+Lsk&+Yu&+Lll&+Y-&+Lsh&+Yap&+Led ea&+Yrri&+Lng&+w&n",
       {SMALL_GOLD_ORE,MEDIUM_GOLD_ORE,0,0,0},
       APPLY_CON, -4,-5,
       APPLY_INT_MAX, 2,3,
       50,50,
       ANTI,
       CLASS_NONE,
       ITEM_WEAR_EARRING,
       	0,0,0,0,
  },
{113, "ugly copper mask",
      "An &+yu&+Lg&+yl&+Ly &+ycopper mask forged by &+W%s &+Llies here.&n",
      "an &+yu&+Lg&+yl&+Ly &+ycopper mask&n",
       {SMALL_COPPER_ORE,MEDIUM_COPPER_ORE,MEDIUM_COPPER_ORE,0,0},
       APPLY_CHA, -10,-12,
       APPLY_STR, 5,7,
       80,50,
       ANTI,
       CLASS_NONE,
       ITEM_WEAR_FACE,
       	0,0,0,0,
  },
{114, "glowing mithril platemail",
      "A suit of &+Yg&+ml&+Yo&+mw&+Yi&+mn&+Yg &+mmithril p&+Ll&+ma&+Lt&+me&+Lm&+ma&+Li&+ml &+wwith &+rspikes forged by &+W%s &+Llies here.&n",
      "a suit of &+Yg&+ml&+Yo&+mw&+Yi&+mn&+Yg &+mmithril p&+Ll&+ma&+Lt&+me&+Lm&+ma&+Li&+ml &+wwith &+rspikes&n",
       {LARGE_MITHRIL_ORE,LARGE_MITHRIL_ORE,LARGE_MITHRIL_ORE,LARGE_MITHRIL_ORE,0},
       APPLY_CON_MAX, 4,5,
       APPLY_STR_MAX, 4,5,
       50,50,
       ANTI,
       CLASS_NONE,
       ITEM_WEAR_BODY,
       	AFF_SENSE_LIFE,0,0,0,
  },
{115, "gold necklace mithril charm",
      "A &+Ygold nec&+mk&+Ylace &+wwith a &+mmithril &+Gd&+ga&+Gg&+gg&+Ge&+gr&+w &+Yc&+mh&+Ya&+mr&+Ym forged by &+W%s &+Llies here.&n",
      "a &+Ygold nec&+mk&+Ylace &+wwith a &+mmithril &+Gd&+ga&+Gg&+gg&+Ge&+gr &+Yc&+mh&+Ya&+mr&+Ym&n",
       {SMALL_MITHRIL_ORE,LARGE_GOLD_ORE,0,0,0},
       APPLY_AGI_MAX, 2,3,
       APPLY_DEX_MAX, 2,3,
       50,50,
       ANTI,
       CLASS_NONE,
       ITEM_WEAR_NECK,
       	0,0,0,0,
  },
{116, "mithril chain cloak",
      "A &+mmithril &+Wc&+wh&+Wa&+wi&+Wn&+wl&+Wi&+wn&+Wk &+ycloak forged by &+W%s &+Llies here.&n",
      "a &+mmithril &+Wc&+wh&+Wa&+wi&+Wn&+wl&+Wi&+wn&+Wk &+ycloak&n",
       {MEDIUM_MITHRIL_ORE,MEDIUM_MITHRIL_ORE,0,0,0},
       APPLY_AGI, -8,-10,
       APPLY_DEX, 2,3,
       50,50,
       ANTI,
       CLASS_NONE,
       ITEM_WEAR_ABOUT,
      	AFF_DETECT_INVISIBLE,0,0,0,
  },
{117, "platinum quiver inlaid",
      "A large &+Wplatinum quiver &+wwith inlaid &+Ygold &+wand &+mmithril &+wdesigns forged by &+W%s &+Llies here.&n",
      "a large &+Wplatinum quiver &+wwith inlaid &+Ygold &+wand &+mmithril &+wdesigns&n",
       {MEDIUM_MITHRIL_ORE,LARGE_GOLD_ORE,0,0,0},
       APPLY_HITROLL, 1,2,
       APPLY_DAMROLL, 0,1,
       50,50,
       ANTI,
       CLASS_NONE,
       ITEM_WEAR_QUIVER,
        AFF_PROT_FIRE,0,0,0,
  },
{118, "mithril shield",
      "A nearly &+rin&+Rvi&+rnc&+Rib&+rle &+mmithril sh&+Lie&+mld with &+Rsharp s&+rp&+Ri&+rk&+Re&+rs&+w forged by &+W%s &+Llies here.&n",
      "a nearly &+rin&+Rvi&+rnc&+Rib&+rle &+mmithril sh&+Lie&+mld with &+Rsharp s&+rp&+Ri&+rk&+Re&+rs&+w&n",
       {MEDIUM_MITHRIL_ORE,LARGE_MITHRIL_ORE,LARGE_MITHRIL_ORE,0,0},
       APPLY_DEX, -6,-8,
       APPLY_DAMROLL, 2,3,
       50,50,
       ANTI,
       CLASS_NONE,
       ITEM_WEAR_SHIELD,
        0,AFF2_PROT_ACID,0,0,
  },
{119, "platinum gold snake bracelet",
      "A &+Wplatinum &+wand &+Ygold b&+Wr&+Ya&+Wc&+Ye&+Wl&+Ye&+Wt &+win the shape of a &+Gsn&+ga&+Gke&+w forged by &+W%s &+Llies here.&n",
      "a &+Wplatinum &+wand &+Ygold b&+Wr&+Ya&+Wc&+Ye&+Wl&+Ye&+Wt &+win the shape of a &+Gsn&+ga&+Gke&+w&n",
       {MEDIUM_GOLD_ORE,MEDIUM_PLATINUM_ORE,0,0,0},
       APPLY_AGI, 6,8,
       APPLY_AGI_MAX, 2,3,
       50,50,
       ANTI,
       CLASS_NONE,
       ITEM_WEAR_WRIST,
        0,0,0,0,
  },
{120, "cloudy shadow mask",
      "A &+bclo&+Bud&+cy &+Lm&+was&+Lk &+wfringed with &+Lshadow &+wforged by &+W%s &+Llies here.&n",
      "a &+bclo&+Bud&+cy &+Lm&+was&+Lk &+wfringed with &+Lshadow&n",
       {MEDIUM_SILVER_ORE,LARGE_SILVER_ORE,MEDIUM_COPPER_ORE,0,0},
       APPLY_AGI, 8,10,
       APPLY_STR, 8,10,
       50,50,
       ANTI,
       CLASS_NONE,
       ITEM_WEAR_FACE,
        AFF_PROT_FIRE,0,0,0,
  },
{121, "jagged gold horns",
      "A &+yjagged &+Lpair of &+Ygold &+Rh&+ror&+Rns forged by &+W%s &+Llies here.&n",
      "a &+yjagged &+Lpair of &+Ygold &+Rh&+ror&+Rns&n",
       {MEDIUM_GOLD_ORE,LARGE_GOLD_ORE,0,0,0},
       APPLY_DAMROLL, 2,3,
       APPLY_SAVING_SPELL, -1,-2,
       50,50,
       ANTI,
       CLASS_NONE,
       ITEM_WEAR_HORN,
        AFF_SENSE_LIFE,0,0,0,
  },
{122, "smooth silver horns",
      "A &+gsm&+Goo&+gth &+ypair of &+wsilver &+Lh&+worn&+Ls forged by &+W%s &+Llies here.&n",
      "a &+gsm&+Goo&+gth &+ypair of &+wsilver &+Lh&+worn&+Ls&n",
       {MEDIUM_SILVER_ORE,SMALL_SILVER_ORE,0,0,0},
       APPLY_CON_MAX, 2,3,
       APPLY_SAVING_SPELL, -1,2,
       50,50,
       ANTI,
       CLASS_NONE,
       ITEM_WEAR_HORN,
        AFF_SENSE_LIFE,0,0,0,
  },
 {123, "sack lightweight lined silver",
       "A &+Llight&+Wweight &+Csack lined in &+Lsilver forged by &+W%s &+Llies here.&n",
       "a &+Llight&+Wweight &+Csack lined in &+Lsilver&n",
        {MEDIUM_SILVER_ORE,SMALL_SILVER_ORE,0,0,0},
        APPLY_MOVE, 12,15,
        APPLY_STR, 6,8,
        50,50,
        ANTI,
        CLASS_NONE,
        ITEM_WEAR_BACK,
         0,0,0,0,
  },
{124, "band silver polished mithril",
      "A &+Lp&+wolish&+Led band of &+wsilver lined with &+mmithril forged by &+W%s &+Llies here.&n",
      "a &+Lp&+wolish&+Led band of &+wsilver lined with &+mmithril&n",
       {MEDIUM_SILVER_ORE,SMALL_MITHRIL_ORE,0,0,0},
       APPLY_MOVE, 26,30,
       APPLY_STR, 8,10,
       50,50,
       ANTI,
       CLASS_NONE,
       ITEM_WEAR_FINGER,
        AFF_PROT_FIRE,0,0,0,
  },
{125, "thin silver ring heart",
      "A thin &+wsilver &+Br&+bin&+bg with a &+Wplatinum &+Rh&+rea&+Rrt forged by &+W%s &+Llies here.&n",
      "a thin &+wsilver &+Br&+bin&+bg with a &+Wplatinum &+Rh&+rea&+Rrt&n",
       {SMALL_SILVER_ORE,SMALL_PLATINUM_ORE,0,0,0},
       APPLY_HIT, 12,15,
       APPLY_STR, 8,10,
       50,50,
       ANTI,
       CLASS_NONE,
       ITEM_WEAR_FINGER,
        0,0,0,0,
  },
 {126, "copper ball star",
       "A &+ycopper &+Gb&+ga&+Gll with a &+Wdangling &+Ygolden &+Ys&+Wt&+Ya&+Wr forged by &+W%s &+Llies here.&n",
       "a &+ycopper &+Gb&+ga&+Gll with a &+Wdangling &+Ygolden &+Ys&+Wt&+Ya&+Wr&n",
        {SMALL_COPPER_ORE,SMALL_GOLD_ORE,0,0,0},
        APPLY_HIT, 10,12,
        APPLY_AGI, 4,5,
        50,50,
        ANTI,
        CLASS_NONE,
        ITEM_WEAR_EARRING,
         0,0,0,0,
  },
{127, "sterling silver snake chain",
      "A &+Cste&+crl&+Cing silver &+Gs&+gnak&+Ge &+Lcha&+Lin forged by &+W%s &+Llies here.&n",
      "a &+Cste&+crl&+Cing silver &+Gs&+gnak&+Ge &+Lcha&+Lin&n",
       {SMALL_SILVER_ORE,SMALL_SILVER_ORE,SMALL_SILVER_ORE,SMALL_SILVER_ORE,0},
       APPLY_CON, 6,7,
       APPLY_SAVING_SPELL, -1,-2,
       50,50,
       ANTI,
       CLASS_NONE,
       ITEM_WEAR_NECK,
        0,AFF2_PROT_GAS,0,0,
    },
{128, "sterling silver chain",
      "A &+Cste&+crl&+Cing silver &+Lcha&+Lin with &+Rtr&+rip&+Rle he&+rart&+Rs forged by &+W%s &+Llies here.&n",
      "a &+Cste&+crl&+Cing silver &+Lcha&+Lin with &+Rtr&+rip&+Rle he&+rart&+Rs&n",
       {SMALL_SILVER_ORE,SMALL_SILVER_ORE,SMALL_SILVER_ORE,SMALL_SILVER_ORE,0},
       APPLY_HIT, 11,12,
       APPLY_CHA, 8,10,
       50,50,
       ANTI,
       CLASS_NONE,
       ITEM_WEAR_NECK,
        0,0,0,0,
  },
{129, "sterling silver chain",
      "A &+Cste&+crl&+Cing silver &+Lcha&+Lin with &+ciron &+cst&+Carfi&+csh forged by &+W%s &+Llies here.&n",
      "a &+Cste&+crl&+Cing silver &+Lcha&+Lin with &+ciron &+cst&+Carfi&+csh&n",
       {SMALL_SILVER_ORE,SMALL_SILVER_ORE,SMALL_SILVER_ORE,SMALL_IRON_ORE,0},
       APPLY_HIT, 11,12,
       APPLY_SAVING_PARA, -1,-2,
       50,50,
       ANTI,
       CLASS_NONE,
       ITEM_WEAR_NECK,
        0,0,0,0,
  },
{130, "sterling silver chain bible",
      "A &+Cste&+crl&+Cing silver &+Lcha&+Lin with a &+mmithril &+Cbi&+Cbl&+Ce forged by &+W%s &+Llies here.&n",
      "a &+Cste&+crl&+Cing silver &+Lcha&+Lin with a &+mmithril &+Cbi&+Cbl&+Ce&n",
       {SMALL_SILVER_ORE,SMALL_SILVER_ORE,SMALL_SILVER_ORE,SMALL_MITHRIL_ORE,0},
       APPLY_WIS_MAX, 2,3,
       APPLY_SAVING_BREATH, -1,-2,
       50,50,
       ANTI,
       CLASS_NONE,
       ITEM_WEAR_NECK,
        0,0,AFF3_SPIRIT_WARD,0,
  },
{131, "magical silver charm",
      "A &+Cma&+cgi&+Ccal silver &+Cch&+Car&+Cm of the &+Mwild&+mmage forged by &+W%s &+Llies here.&n",
      "a &+Cma&+cgi&+Ccal silver &+Cch&+Car&+Cm of the &+Mwild&+mmage&n",
       {SMALL_SILVER_ORE,SMALL_SILVER_ORE,MEDIUM_SILVER_ORE,SMALL_MITHRIL_ORE,0},
        APPLY_INT_MAX, 0,2,
        APPLY_SAVING_PARA, -1,-2,
        50,50,
        ANTI,
        CLASS_NONE,
        ITEM_WEAR_WRIST,
         0,AFF2_DETECT_MAGIC,0,0,
  },
{132, "magical copper charm",
      "A &+Cma&+cgi&+Ccal &+ycopper &+Cch&+Car&+Cm with &+Linscr&+wipti&+Lons forged by &+W%s &+Llies here.&n",
      "a &+Cma&+cgi&+Ccal &+ycopper &+Cch&+Car&+Cm with &+Linscr&+wipti&+Lons&n",
       {SMALL_COPPER_ORE,SMALL_COPPER_ORE,SMALL_COPPER_ORE,LARGE_COPPER_ORE,0},
       APPLY_HIT, 10,12,
       APPLY_SAVING_SPELL, -1,-2,
       50,50,
       ANTI,
       CLASS_NONE,
       ITEM_WEAR_WRIST,
        0,AFF2_DETECT_MAGIC,0,0,
  },
};
